# Copyright 2016, 2017 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

python: "2.7"

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

env:
  matrix:
    - BOGUS_JOB=true

matrix:

  exclude:
    - env: BOGUS_JOB=true

  include:
    # cmake self-test
    - os: linux
      env: TEST_CMAKE=TRUE #Only for easier identification in travis web gui
      install:
        - git clone --depth 1 https://github.com/boostorg/assert.git ../assert
        - git clone --depth 1 https://github.com/boostorg/config.git ../config
        - git clone --depth 1 https://github.com/boostorg/static_assert.git ../static_assert
        - git clone --depth 1 https://github.com/boostorg/type_traits.git ../type_traits

      script:
        - mkdir __build__ && cd __build__
        - cmake ../test/test_cmake
        - cmake --build .

# gcc, Linux
    - os: linux
      env: TOOLSET=gcc COMPILER=g++ CXXSTD64=03,11

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.7 CXXSTD64=03,11 CXXSTD32=03,11
      addons:
        apt:
          packages:
            - g++-4.7
            - g++-4.7-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.8 CXXSTD64=03,11 CXXSTD32=03,11
      addons:
        apt:
          packages:
            - g++-4.8
            - g++-4.8-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.9 CXXSTD64=03,11 CXXSTD32=03,11
      addons:
        apt:
          packages:
            - g++-4.9
            - g++-4.9-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-5 CXXSTD64=03,11,14 CXXSTD32=03,11
      addons:
        apt:
          packages:
            - g++-5
            - g++-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD64=03,11,14,1z CXXSTD32=03,11
      addons:
        apt:
          packages:
            - g++-6
            - g++-6-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-7 CXXSTD64=03,11,14,17 CXXSTD32=03,11
      addons:
        apt:
          packages:
            - g++-7
            - g++-7-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-8 CXXSTD64=03,11,14,17,03-gnu,11-gnu,14-gnu,17-gnu CXXSTD32=03,11
      addons:
        apt:
          packages:
            - g++-8
            - g++-8-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

# clang, Linux
    - os: linux
      env: TOOLSET=clang COMPILER=clang++ CXXSTD64=03,11

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.5 CXXSTD64=03,11 CXXSTD32=03,11
      addons:
        apt:
          packages:
            - clang-3.5
            - g++-4.9-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.6 CXXSTD64=03,11 CXXSTD32=03,11
      addons:
        apt:
          packages:
            - clang-3.6
            - g++-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.7 CXXSTD64=03,11 CXXSTD32=03,11
      addons:
        apt:
          packages:
            - clang-3.7
            - g++-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.8 CXXSTD64=03,11,14,1z CXXSTD32=03,11
      addons:
        apt:
          packages:
            - clang-3.8
            - g++-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.9 CXXSTD64=03,11,14,1z CXXSTD32=03,11
      addons:
        apt:
          packages:
            - clang-3.9
            - g++-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-4.0 CXXSTD64=03,11,14,1z CXXSTD32=03,11
      addons:
        apt:
          packages:
            - clang-4.0
            - g++-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-5.0 CXXSTD64=03,11,14,1z CXXSTD32=03,11
      addons:
        apt:
          packages:
            - clang-5.0
            - g++-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-6.0 CXXSTD64=03,11,14,17 CXXSTD32=03,11
      addons:
        apt:
          packages:
            - clang-6.0
            - g++-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-7 CXXSTD64=03,11,14,17 CXXSTD32=03,11
      addons:
        apt:
          packages:
            - clang-7
            - g++-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7

# clang, OS X, 64-bit
    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD64=03,11,14,1z
      osx_image: xcode9.4


install:
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/boostdep
  - git submodule update --init tools/build
  - git submodule update --init tools/inspect
  - git submodule update --init libs/config
  - cp -r $TRAVIS_BUILD_DIR/* libs/atomic
  - python tools/boostdep/depinst/depinst.py atomic
  - ./bootstrap.sh
  - ./b2 headers

script:
  - |-
    echo "using $TOOLSET : : $COMPILER ;" > ~/user-config.jam
  - if [ -n "$CXXSTD64" ]; then echo ""; echo "Testing 64-bit targets"; echo ""; ./b2 -j3 libs/atomic/test toolset=$TOOLSET address-model=64 cxxstd=$CXXSTD64; fi
  - if [ -n "$CXXSTD32" ]; then echo ""; echo "Testing 32-bit targets"; echo ""; ./b2 -j3 libs/atomic/test toolset=$TOOLSET address-model=32 cxxstd=$CXXSTD32; fi

notifications:
  email:
    on_success: always
